import getCurrentUser from './actions/getCurrentUser'
import './globals.css'
import ToasterProvider from './components/ToasterProvider'
import Navbar from './components/Navbar'

export const metadata = {
  title: 'Jokes',
  description: 'Generated by create next app',
}



export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const currentUser = await getCurrentUser();

  return (
    <html>
      <body className='block m-0 bg-[#ececec]'>
        <ToasterProvider />
        <Navbar currentUser={currentUser} />
        {children}
      </body>
    </html>
  )
}
